# Generated by Django 3.2.6 on 2021-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20210811_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended_user_details',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
